### ISSUE TITLE
Compatibility issue with ACFBlocks

### ISSUE THREAD

**Issue by munirkamal** [phpbits/block-options#7]
Hi,

I was trying to test EditorsKit with [ACFBlocks plugin](https://wordpress.org/plugins/acf-blocks) which is built on top of ACF Pro v5.8 which introduces the PHP Block Building Framework. And Looks like there is a compatibility issue which doesn't load the render the blocks in editor when EditorKits plugin is active.

https://cl.ly/6e81abc5e8c1

Can you please check this?

**Comment by phpbits** [comment]
@munirkamal Thanks a lot for reporting the issue. I'll take a look and let you know when I've fixed the issue. Thanks!

**Comment by phpbits** [comment]
@munirkamal It seems that ACF blocks support is fairly new and doesn't support several Gutenberg filters yet. You can use this branch for the meantime : https://github.com/phpbits/block-options/tree/fix/acf-blocks-issue but the editorskit visibility won't work because ACF blocks is not adding the custom classNames. Thanks!

**Comment by phpbits** [comment]
@munirkamal Here's the ticket for this issue : https://core.trac.wordpress.org/ticket/45882 . Thanks!

**Comment by phpbits** [comment]
@munirkamal I've finally found a workaround to atleast prevent printing the issue :) Fixes will be added on the next version update. Thanks!

**Comment by phpbits** [comment]
@munirkamal  Fixed the issue on the new 1.9.1 plugin version. Thanks a lot!
